%Create Aero.FixedWing and Aero.FixedWing.State objects to calculate the static stability derivatives.
function [myAircraft, CruiseState] = createFixedWing(aircraft_Mass, wing, hTail, initialValues)

myProperties = Aero.Aircraft.Properties('Name', 'Regular Class Aircraft', ...
                                        'Type', 'RC Aircraft', ...
                                        'Version', '1.0', ...
                                        'Description', 'SAE Regular Class Initial Design');

myAircraft = Aero.FixedWing('Properties', myProperties, ...
                            'UnitSystem', 'Metric', ...
                            'AngleSystem', 'Radians', ...
                            'TemperatureSystem', 'Celsius', ...
                            'ReferenceArea', evaluate(wing.PlanformArea, initialValues), ...
                            'ReferenceSpan', 2*evaluate(wing.HalfSpan, initialValues), ...
                            'ReferenceLength', evaluate(hTail.Xac + 3/4*hTail.Chord, initialValues));

CruiseState = Aero.FixedWing.State('UnitSystem', myAircraft.UnitSystem, ...
                                   'AngleSystem', myAircraft.AngleSystem, ...
                                   'TemperatureSystem', myAircraft.TemperatureSystem, ...
                                   'Mass', evaluate(aircraft_Mass, initialValues), ...
                                   'U', 10, ...
                                   'AltitudeMSL', 0);
%Copyright 2022 The MathWorks, Inc.
